In [1]:
from geopy.geocoders import Nominatim
import numpy as np
import pandas as pd
from math import radians, cos, sin, asin, sqrt

by using the function below, u will get a dataframe of the districts with their lat and long

In [2]:
def get_location_coordinates(loc_series, language='en'):
#   loc_series must be the column of english district in our actual dataframe
#   there must be no NaN values for this function to work 
    unique_district = loc_series.astype(str)
    unique_district = unique_district.unique().tolist()
    loc_teh = [s + ' tehran' for s in unique_district]
    loc = []
    lats = []
    longs = []
    geolocator = Nominatim(user_agent="your_app_name")
    for item in loc_teh:
        location = geolocator.geocode(item)
        if location:
            loc.append(item.removesuffix('tehran'))
            lats.append(location.latitude)
            longs.append(location.longitude)
    coordinates_df = pd.DataFrame({'loc_name':loc,'lat':lats,'long':longs})
    return coordinates_df

distance(lat1, lon1, lat2, lon2) will return the distance between two locations

In [3]:
def distance(lat1,lon1,lat2,lon2): 
    lon1 = radians(lon1) 
    lon2 = radians(lon2) 
    lat1 = radians(lat1) 
    lat2 = radians(lat2)  
    dlon = lon2 - lon1  
    dlat = lat2 - lat1 
    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * asin(sqrt(a))  
    r = 6371
    dist_km = c * r
    return(dist_km)

this function will add a column to coordinates_df which shows if there is a subway station near the regions or not.

In [4]:
def near_metro(coordinates_df,metro_df,min_dist):
    region_len = len(coordinates_df)
    metro_len = len(metro_df)
    region = []
    near_dist = []
    for i in range(region_len):
        for j in range(metro_len):
            dist = distance(coordinates_df.iloc[i,1],coordinates_df.iloc[i,2],metro_df.iloc[j,1],metro_df.iloc[j,2])
            if dist <= min_dist:
                region.append(coordinates_df.iloc[i,0])
                near_dist.append(dist)
                break
    if_near = pd.DataFrame({'region':region})
    coordinates_df['if_near'] = coordinates_df.iloc[:,0].isin(if_near['region']).astype(int)
    return coordinates_df

## Example

In [5]:
metro_df = pd.read_csv('metro.csv')

In [6]:
dist_list = ['chitgar', 'shahrak-e-gharb', 'darrous', 'sharif', 'shokoofeh',
       'nazi-abad', 'tehran-zanjan', 'salamat', 'north-shahran',
       'pirouzi', 'east-tehranpars', 'heravi', 'fallah', 'mahmoodiyeh',
       'darabad', 'mobarak-abad-e-beheshti', 'khani-abad-no', 'jeyhoun',
       'sabalan', 'sazman-ab', 'jamalzadeh', 'vardavard',
       'central-janat-abad', 'mirdamad', 'north-sohrevardi', 'eram',
       'west-shahrak-e-golestan', 'kooy-e-ferdos', 'zafaraniyeh',
       'poonak', 'dehkade-olympic', 'soleymani', 'tehran-kerman',
       'chitgar-lake', 'sazamn-barnameh', 'estakhr', 'qeytariyeh',]
loc_df = pd.DataFrame({'loc_name':dist_list})

In [7]:
coordinates_df = get_location_coordinates(loc_df['loc_name'], language='en')

In [8]:
near_metro(coordinates_df,metro_df,1)

             loc_name        lat       long  if_near
0            chitgar   35.716956  51.243865        1
1    shahrak-e-gharb   35.759061  51.376042        1
2             sharif   35.703101  51.352451        1
3          shokoofeh   35.707866  51.370302        0
4          nazi-abad   35.641538  51.402494        0
5            salamat   35.754919  51.452311        0
6      north-shahran   35.773359  51.288250        0
7            pirouzi   35.690905  51.457152        1
8    east-tehranpars   35.741104  51.546615        0
9             heravi   35.772042  51.473187        1
10            fallah   35.775207  51.338079        0
11       mahmoodiyeh   35.794141  51.439894        0
12           darabad   35.861468  51.497889        0
13     khani-abad-no   35.632836  51.389491        0
14           jeyhoun   35.697901  51.363130        0
15           sabalan   35.718241  51.464570        0
16         sazman-ab   35.739031  51.289273        0
17        jamalzadeh   35.697220  51.388284        1
18         vardavard   35.743826  51.150633        0
19          mirdamad   35.760101  51.433960        0
20  north-sohrevardi   35.735838  51.441783        1
21              eram   35.729082  51.288112        0
22       zafaraniyeh   35.810049  51.418693        0
23            poonak   35.765428  51.342472        0
24   dehkade-olympic   35.749373  51.263954        0
25         soleymani   35.753256  51.455528        0
26      chitgar-lake   35.745160  51.214036        0
27           estakhr   35.757210  51.563112        0
28        qeytariyeh   35.795563  51.444599        0

In [9]:
coordinates_df

             loc_name        lat       long  if_near
0            chitgar   35.716956  51.243865        1
1    shahrak-e-gharb   35.759061  51.376042        1
2             sharif   35.703101  51.352451        1
3          shokoofeh   35.707866  51.370302        0
4          nazi-abad   35.641538  51.402494        0
5            salamat   35.754919  51.452311        0
6      north-shahran   35.773359  51.288250        0
7            pirouzi   35.690905  51.457152        1
8    east-tehranpars   35.741104  51.546615        0
9             heravi   35.772042  51.473187        1
10            fallah   35.775207  51.338079        0
11       mahmoodiyeh   35.794141  51.439894        0
12           darabad   35.861468  51.497889        0
13     khani-abad-no   35.632836  51.389491        0
14           jeyhoun   35.697901  51.363130        0
15           sabalan   35.718241  51.464570        0
16         sazman-ab   35.739031  51.289273        0
17        jamalzadeh   35.697220  51.388284        1
18         vardavard   35.743826  51.150633        0
19          mirdamad   35.760101  51.433960        0
20  north-sohrevardi   35.735838  51.441783        1
21              eram   35.729082  51.288112        0
22       zafaraniyeh   35.810049  51.418693        0
23            poonak   35.765428  51.342472        0
24   dehkade-olympic   35.749373  51.263954        0
25         soleymani   35.753256  51.455528        0
26      chitgar-lake   35.745160  51.214036        0
27           estakhr   35.757210  51.563112        0
28        qeytariyeh   35.795563  51.444599        0